import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const defaultEndpoint = "https://dog.ceo/api/breeds/image/random/3";

export async function getServerSideProps() {
  const res = await fetch(defaultEndpoint);
  const { message: data } = await res.json();
  
  // const res = await fetch(`https://dog.ceo/api/breeds/${breed}/random/3`);
  // const breed = req.query['breed'].toString()

  return {
    props: { data },
  };
}

export default function Home({ data }) {
  console.log("data", data);
  return (
    <div className={styles.container}>
      <Head>
        <title>Dog Breed App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="grid">
          {data.map((img) => (
            <img
              className="breed"
              src={img}
              alt="{breed}"
              width={240}
              height={240}
            />
          ))}
        </div>
      </main>
    </div>
  );
}
