import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const defaultEndpoint = "https://dog.ceo/api/breeds/image/random/9";

export async function getServerSideProps() {
  let time1 = performance.now();
  const res = await fetch(defaultEndpoint);
  const { message: dogs } = await res.json();
  let time2 = performance.now();
  const secs = (time2 - time1).toFixed(2);
  
  return {
    props: { dogs, secs }
  };
}

export default function Home({ dogs, secs }) {

  const RenderDogData = (data) => {
    return data.map((dog, idx) => {
      const url = new URL(dog);
      const path = url.pathname;
      const breed = path.split('/')
      const word = breed[2];

      const breedName = word.replace('-', ' ').replace(/(?:^|\s)\S/g, a => a.toUpperCase());
         
      // const splitBreed = word.replace(/-/, ' ').charAt(0).toUpperCase()
      // + word.slice(1);
      // console.log(splitBreed)

      return (
        <div key={idx}>
          <Image
                id={idx}
                src={dog}
                alt={breedName[2] || idx}
                width={240}
                height={240}
          />
          <h3>{breedName}</h3>
          <h5>Time to fetch data: {secs} ms</h5>
         
        </div>
      )
    })
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Dog Breed App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>

        <div className="grid">
          {RenderDogData(dogs)}
          </div>
 
      </main>
    </div>
  );
}
